Busy wait MPI receive to remove unidist.get contention problem
modin-project/unidist pull request #12
Opened 2021-11-09 19:52 UTC by no-ponomarev

Modin plasticc benchmark reveals heavy contention problem when using all CPU cores and MPI backend. One heavy worker task contents with `unidist.get` receive operation, which previously never went to sleep.

2021-11-09 20:02 UTC, YarShev requested changes
Please, follow commit message rules like in Modin.

2021-11-09 20:17 UTC, prutskov commented
Performance of `unidist` should be checked on the all our benchmarks (census, ny_taxi, plasticc) before merging PR to exclude including regression and to confirm perf improvements.

@no-ponomarev did you check this?

2021-11-10 12:31 UTC, no-ponomarev commented
I have checked plasticc, census and ny_taxi on full mlp01 machine. Performance of other benchmarks did not changed.

2021-11-10 12:33 UTC, prutskov commented
> @prutskov, I have checked plasticc, census and ny_taxi on full mlp01 machine. Performance of other benchmarks have not changed.

ok, thanks!

2021-11-10 12:40 UTC, prutskov approved these changes
LGTM

2021-11-10 12:44 UTC, prutskov commented
@no-ponomarev, sign your commit using command:
```
git commit --amend -s
```

Before this, please set-up your name/email correctly in git config

2021-11-10 13:03 UTC, merged

2021-11-10 13:21 UTC, YarShev commented
@no-ponomarev , please read the rules for committers that we follow. https://modin.readthedocs.io/en/latest/contributing.html#general-rules-for-committers